"use client";

import { useState } from "react";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Modal } from "@/components/ui/modal";
import { Switch } from "@/components/ui/switch";
import { Tag } from "@/components/ui/tag";
import { usePortal } from "@/components/portal/portal-context";
import type { SearchEngine } from "@/types/portal";

const healthTone = (health: SearchEngine["health"]) => health === "Healthy" ? "green" : health === "Disabled" || health === "Unknown" ? "slate" : "amber" as const;
const displayTime = (value: string, locale: string) => value === "—" ? "—" : new Intl.DateTimeFormat(locale, { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value));

export function EnginesPage() {
  const { engines, settings, locale, notify, refresh, setUsageLogs } = usePortal();
  const english = locale === "en";
  const [testing, setTesting] = useState<SearchEngine | null>(null); const [query, setQuery] = useState("lazycat search"); const [batching, setBatching] = useState(false); const [lastResult, setLastResult] = useState<{ engine: string; count: number; latency: number } | null>(null);
  const enabled = engines.filter((engine) => engine.enabled);
  const t = english ? { title: "Search engine management", subtitle: "Monitor upstream health, response latency, and search-mode policy", test: "Test", batch: "Run concurrent health checks", enabled: "Enabled", default: "Default" } : { title: "搜索引擎管理 (Providers Management)", subtitle: "实时监测 9 大搜索源上游健康度、响应延迟与 Search Mode 策略", test: "测试", batch: "运行并发健康测试", enabled: "启用", default: "默认" };
  const patch = async (id: string, value: object) => { try { await api.updateEngine(id, value); await refresh(); } catch (error) { notify(error instanceof Error ? error.message : "更新失败", "error"); } };
  const test = async () => { if (!testing) return; try { const result = await api.testEngine(testing.id, query); setLastResult({ engine: testing.name, count: Number(result.resultCount), latency: Number(result.latencyMs) }); setUsageLogs((items) => [{ id: `engine-test-${Date.now()}`, channel: "Web", operation: "engineTest", token: "—", engines: [testing.name], latency: Number(result.latencyMs), cacheHit: false, resultCount: Number(result.resultCount), status: "Success", errorCode: "—", createdAt: new Date().toISOString() }, ...items]); await refresh(); } catch (error) { notify(error instanceof Error ? error.message : "测试失败", "error"); } };
  const batch = async () => { setBatching(true); try { const queue = [...enabled]; let success = 0; const workers = Array.from({ length: Math.min(Math.max(1, settings.engineConcurrency), queue.length) }, async () => { while (queue.length) { const engine = queue.shift(); if (!engine) return; try { await api.testEngine(engine.id, "lazycat search"); success += 1; } catch { /* individual failures are persisted by the service */ } } }); await Promise.all(workers); await refresh(); notify(english ? `${success}/${enabled.length} checks completed.` : `${success}/${enabled.length} 个健康检查已完成。`, success === enabled.length ? "success" : "info"); } finally { setBatching(false); } };
  return <section className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-extrabold tracking-tight text-slate-900">{t.title}</h1><p className="mt-1 text-xs text-slate-500">{t.subtitle}</p></div><Button variant="secondary" disabled={batching || !enabled.length} onClick={() => void batch()}>{batching ? "↻ …" : "↻"} {t.batch}</Button></div>
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-bold text-slate-900">{english ? "Provider status" : "Provider 状态"}</h2><p className="mt-1 text-xs text-slate-400">{english ? "Toggles update the saved provider configuration and the portal selection." : "开关会更新已保存的 Provider 配置与门户可选项。"}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">{english ? "Engine" : "引擎"}</th><th className="p-4">{t.enabled}</th><th className="p-4">{t.default}</th><th className="p-4">Search Mode</th><th className="p-4">{english ? "Last test" : "最近测试"}</th><th className="p-4">{english ? "Health" : "健康状态"}</th><th className="p-4">{english ? "Latency" : "延迟"}</th><th className="p-4">{english ? "Last error" : "最近错误"}</th><th className="p-4">{english ? "Action" : "操作"}</th></tr></thead><tbody className="divide-y divide-slate-100 font-mono">{engines.map((engine) => <tr key={engine.id} className="text-slate-700"><td className="p-4 font-sans font-bold text-slate-900">{engine.name}</td><td className="p-4"><Switch label={`${engine.name} ${t.enabled}`} checked={engine.enabled} onChange={(value) => void patch(engine.id, { enabled: value })} /></td><td className="p-4"><Switch label={`${engine.name} ${t.default}`} checked={engine.isDefault} onChange={(value) => void patch(engine.id, { isDefault: value })} /></td><td className="p-4"><Tag tone={engine.mode === "Request" ? "blue" : "neutral"}>{engine.mode}</Tag></td><td className="p-4 text-[11px]">{displayTime(engine.lastTestAt, english ? "en-US" : "zh-CN")}</td><td className="p-4"><Tag tone={healthTone(engine.health)}>{engine.health}</Tag></td><td className="p-4">{engine.latency === null ? "—" : `${engine.latency}ms`}</td><td className="max-w-48 truncate p-4 text-[11px] text-slate-400" title={engine.lastError}>{engine.lastError}</td><td className="p-4"><Button variant="secondary" className="min-h-7 px-2 text-[11px]" disabled={!engine.enabled} onClick={() => { setTesting(engine); setLastResult(null); }}>{t.test}</Button></td></tr>)}</tbody></table></div></div>
    {testing ? <Modal title={`${t.test} · ${testing.name}`} onClose={() => setTesting(null)} footer={<><Button variant="secondary" onClick={() => setTesting(null)}>{english ? "Close" : "关闭"}</Button><Button onClick={() => void test()}>{english ? "Run test" : "发起测试"}</Button></>}><p className="mb-4 text-xs leading-5 text-slate-500">{english ? "This sends one real search request to the selected upstream." : "此操作会向所选上游发起一次真实搜索请求。"}</p><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-700">{english ? "Selected engine" : "选择的引擎"}<Input className="mt-1" readOnly value={testing.name} /></label><label className="text-xs font-bold text-slate-700">{english ? "Test query" : "测试关键词"}<Input className="mt-1" value={query} onChange={(event) => setQuery(event.target.value)} /></label></div>{lastResult ? <div className="mt-4 rounded-xl border border-emerald-100 bg-emerald-50 p-3 font-mono text-xs text-emerald-800">{testing.name}: {lastResult.count} results · {lastResult.latency}ms</div> : <div className="mt-4 rounded-xl bg-slate-950 p-3 font-mono text-[11px] text-slate-300">&gt; ready to test {testing.name}</div>}</Modal> : null}
  </section>;
}
