"use client";

import { useState } from "react";
import { api } from "@/lib/api";
import { clientTemplates } from "@/lib/mock-data";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Modal } from "@/components/ui/modal";
import { Select } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Tag } from "@/components/ui/tag";
import { Icon } from "@/components/ui/icon";
import { usePortal } from "@/components/portal/portal-context";
import type { McpToken } from "@/types/portal";

const formatDate = (value: string, locale: string) => value === "—" ? value : new Intl.DateTimeFormat(locale, { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value));

export function McpPage() {
  const { locale, tools, tokens, setTools, notify, refresh } = usePortal(); const english = locale === "en";
  const configuredBase = process.env.NEXT_PUBLIC_API_BASE_URL; const endpointBase = configuredBase && /^https?:\/\//.test(configuredBase) ? configuredBase : (typeof window === "undefined" ? "http://localhost" : window.location.origin); const endpoint = new URL("/mcp", endpointBase).toString();
  const [open, setOpen] = useState(false); const [secret, setSecret] = useState<string | null>(null); const [testReport, setTestReport] = useState<string[] | null>(null); const [activeConfig, setActiveConfig] = useState<keyof typeof clientTemplates>("WorkBuddy");
  const [name, setName] = useState(english ? "New integration" : "新接入方"); const [scope, setScope] = useState<McpToken["scope"]>("all"); const [rpmLimit, setRpmLimit] = useState(60); const [dailyLimit, setDailyLimit] = useState(5000); const [expiry, setExpiry] = useState("30");
  const copy = async (value: string) => { try { await navigator.clipboard?.writeText(value); notify(english ? "Copied to clipboard." : "已复制到剪贴板。"); } catch { notify(english ? "Clipboard access was not granted." : "浏览器未授予剪贴板权限。", "error"); } };
  const config = clientTemplates[activeConfig].replaceAll("https://search.example.com/mcp", endpoint);
  const changeTool = async (toolName: string, enabled: boolean) => { try { await api.updateMcpTools({ [toolName]: enabled }); setTools((items) => items.map((tool) => tool.name === toolName ? { ...tool, enabled } : tool)); notify(english ? "Tool exposure updated." : "Tool 暴露状态已更新。"); } catch (error) { notify(error instanceof Error ? error.message : "保存失败", "error"); } };
  const create = async () => { try { const expiresAt = expiry === "never" ? null : new Date(Date.now() + Number(expiry) * 86_400_000).toISOString(); const token = await api.createToken({ name, scope, rpmLimit, dailyLimit, expiresAt }); setOpen(false); setSecret(token.secret); await refresh(); } catch (error) { notify(error instanceof Error ? error.message : "创建失败", "error"); } };
  const changeToken = async (id: string, status: "active" | "disabled" | "revoked") => { try { await api.updateToken(id, status); await refresh(); } catch (error) { notify(error instanceof Error ? error.message : "更新失败", "error"); } };
  const runTest = async () => { try { const liveTools = await api.mcp(); setTestReport(["[✓] 管理端点返回成功", `[✓] 已读取 ${liveTools.length} 个 Tools 声明`, `[✓] 当前启用 ${liveTools.filter((tool) => tool.enabled).length} 个 Tools`, "[i] 带 Token 的 MCP initialize 需由外部客户端执行。"]); } catch (error) { setTestReport([`[×] ${error instanceof Error ? error.message : "管理端点不可用"}`]); } };
  return <section className="mx-auto max-w-5xl space-y-6 pb-16">
    <div><h1 className="text-2xl font-extrabold tracking-tight text-slate-900">{english ? "MCP service management (Model Context Protocol)" : "MCP 服务管理 (Model Context Protocol)"}</h1><p className="mt-1 text-xs text-slate-500">{english ? "Expose remote tools compatible with the Streamable HTTP transport." : "对外暴露符合 Anthropic MCP 规范的远程 Tools，主推 Streamable HTTP 传输协议"}</p></div>
    <Card className="space-y-4 rounded-2xl border-blue-100 bg-gradient-to-br from-white via-blue-50/20 to-sky-50/20 p-6"><div className="flex items-center justify-between"><span className="flex items-center text-sm font-bold text-slate-900"><Icon name="broadcast" weight="fill" className="mr-2 text-xl text-blue-600" />MCP Service Status</span><Tag tone="green">● Active · 配置状态</Tag></div><div className="flex items-center justify-between rounded-xl border border-slate-800 bg-slate-900 p-3.5 font-mono text-xs text-slate-100 shadow-inner"><div><p className="mb-0.5 text-[10px] text-slate-400">STREAMABLE HTTP ENDPOINT</p><code className="font-bold text-emerald-400">{endpoint}</code></div><button type="button" onClick={() => void copy(endpoint)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-white" aria-label="复制 MCP Endpoint"><Icon name="copy" /></button></div><div className="flex flex-wrap items-center justify-between gap-2 border-t border-slate-100 pt-3 text-xs text-slate-600"><span className="font-semibold">Transport 协议模式</span><div className="flex gap-3"><span className="font-bold text-blue-700">Streamable HTTP（推荐）</span><span className="text-slate-300">|</span><span className="text-slate-400">Legacy SSE（默认关闭）</span></div></div></Card>
    <Card className="overflow-hidden rounded-2xl"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 bg-slate-50/50 p-4"><h2 className="text-sm font-bold text-slate-900">暴露的 Tools 声明 ({tools.length} Tools)</h2><span className="text-xs text-slate-400">站点专用 fetch Tool 可由管理员单独启停</span></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-slate-200 bg-slate-100/70 text-[10px] font-bold uppercase text-slate-500"><th className="p-3">Tool 名称</th><th className="p-3">描述</th><th className="p-3">关键参数</th><th className="p-3 text-center">状态 / 启停</th></tr></thead><tbody className="divide-y divide-slate-100 font-mono text-xs text-slate-700">{tools.map((tool) => <tr key={tool.name}><td className="p-3 font-bold text-slate-900">{tool.name}</td><td className="p-3 font-sans text-slate-600">{tool.description}</td><td className="p-3 text-[11px] text-slate-500">{tool.parameters}</td><td className="p-3"><div className="flex justify-center"><Switch label={`${tool.name} enabled`} checked={tool.enabled} onChange={(enabled) => void changeTool(tool.name, enabled)} /></div></td></tr>)}</tbody></table></div></Card>
    <Card className="overflow-hidden rounded-2xl"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 bg-slate-50/50 p-5"><div><h2 className="text-base font-bold text-slate-900">Access Tokens (MCP 鉴权密钥)</h2><p className="mt-0.5 text-xs text-slate-500">外部 Agent 通过 <code className="font-semibold text-blue-600">Authorization: Bearer ows_...</code> 鉴权</p></div><Button className="rounded-xl" onClick={() => setOpen(true)}>＋ 新建 Access Token</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left"><thead><tr className="border-b border-slate-200 bg-slate-100/70 text-[10px] font-bold uppercase text-slate-500"><th className="p-4">名称</th><th className="p-4">Prefix</th><th className="p-4">Scope</th><th className="p-4">创建时间</th><th className="p-4">限流 (Min/Day)</th><th className="p-4">过期时间</th><th className="p-4">最近使用</th><th className="p-4">今日调用</th><th className="p-4">状态</th><th className="p-4 text-right">操作</th></tr></thead><tbody className="divide-y divide-slate-100 font-mono text-xs">{tokens.length ? tokens.map((token) => <tr key={token.id}><td className="p-4 font-sans font-bold text-slate-800">{token.name}</td><td className="p-4 text-slate-600">{token.prefix}••••</td><td className="p-4"><Tag tone="blue">{token.scope}</Tag></td><td className="p-4 text-[11px] text-slate-600">{formatDate(token.createdAt, english ? "en-US" : "zh-CN")}</td><td className="p-4 text-slate-600">{token.rpmLimit || "—"}/{token.dailyLimit || "—"}</td><td className="p-4 text-slate-600">{formatDate(token.expiresAt, english ? "en-US" : "zh-CN")}</td><td className="p-4 text-slate-600">{token.lastUsedAt === "—" ? "从未" : formatDate(token.lastUsedAt, english ? "en-US" : "zh-CN")}</td><td className="p-4 text-slate-600">{token.usageToday}</td><td className="p-4"><Tag tone={token.status === "Active" ? "green" : token.status === "Disabled" ? "amber" : "red"}>{token.status}</Tag></td><td className="p-4 text-right whitespace-nowrap">{token.status !== "Revoked" ? <><Button variant="ghost" className="min-h-7 px-2 text-[11px]" onClick={() => void changeToken(token.id, token.status === "Active" ? "disabled" : "active")}>{token.status === "Active" ? "禁用" : "启用"}</Button><Button variant="ghost" className="min-h-7 px-2 text-[11px] text-red-700" onClick={() => void changeToken(token.id, "revoked")}>撤销</Button></> : <span className="text-slate-400">—</span>}</td></tr>) : <tr><td colSpan={10} className="p-8 text-center text-slate-400">尚未创建 Access Token。</td></tr>}</tbody></table></div></Card>
    <div className="grid gap-5 md:grid-cols-2"><Card className="rounded-2xl p-5"><h2 className="text-sm font-bold text-slate-900">客户端接入配置模板 (5 Templates)</h2><div className="mt-3 flex gap-1.5 overflow-x-auto border-b border-slate-200 pb-2 text-xs">{Object.keys(clientTemplates).map((key) => <button key={key} type="button" onClick={() => setActiveConfig(key as keyof typeof clientTemplates)} className={`shrink-0 rounded-lg px-3 py-1.5 font-bold ${activeConfig === key ? "bg-blue-600 text-white" : "text-slate-600 hover:bg-slate-100"}`}>{key}</button>)}</div><pre className="mt-3 max-h-52 overflow-auto rounded-xl border border-slate-800 bg-slate-900 p-4 text-xs leading-relaxed text-emerald-400">{config}</pre><Button variant="quiet" className="mt-3 w-full rounded-xl" onClick={() => void copy(config)}><Icon name="copy" /> 复制配置代码</Button></Card><Card className="flex flex-col justify-between space-y-4 rounded-2xl p-5"><div><h2 className="mb-1 text-sm font-bold text-slate-900">MCP Endpoint 连接测试</h2><p className="text-xs text-slate-500">读取管理元数据和 Tools 列表；完整 Endpoint 握手需由客户端使用 Token 验证。</p></div><pre className="min-h-28 whitespace-pre-wrap rounded-xl border border-slate-200 bg-slate-50 p-4 text-xs leading-6 text-slate-700">{testReport?.join("\n") ?? "// 点击下方按钮开始测试..."}</pre><Button className="w-full rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600" onClick={() => void runTest()}><Icon name="play" weight="fill" /> 运行管理端检查</Button></Card></div>
    {open ? <Modal title="新建 Access Token" onClose={() => setOpen(false)} footer={<><Button variant="secondary" onClick={() => setOpen(false)}>取消</Button><Button onClick={() => void create()}>生成 Token</Button></>}><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-700 sm:col-span-2">Token 名称<Input className="mt-1" value={name} onChange={(event) => setName(event.target.value)} /></label><label className="text-xs font-bold text-slate-700">Scope<Select className="mt-1 w-full" value={scope} onChange={(event) => setScope(event.target.value as McpToken["scope"])}><option value="all">search, fetch</option><option value="search">search</option><option value="fetch">fetch</option></Select></label><label className="text-xs font-bold text-slate-700">有效期<Select className="mt-1 w-full" value={expiry} onChange={(event) => setExpiry(event.target.value)}><option value="30">30 天</option><option value="90">90 天</option><option value="365">1 年</option><option value="never">永不过期</option></Select></label><label className="text-xs font-bold text-slate-700">每分钟限流<Input className="mt-1" type="number" min={1} value={rpmLimit} onChange={(event) => setRpmLimit(Number(event.target.value))} /></label><label className="text-xs font-bold text-slate-700">每日调用上限<Input className="mt-1" type="number" min={1} value={dailyLimit} onChange={(event) => setDailyLimit(Number(event.target.value))} /></label><p className="text-xs text-amber-700 sm:col-span-2">完整 Secret 仅展示一次，数据库只保存其 Hash 摘要。</p></div></Modal> : null}{secret ? <Modal title="Access Token 创建成功" onClose={() => setSecret(null)} footer={<Button onClick={() => { void copy(secret); setSecret(null); }}>我已保存</Button>}><p className="mb-3 text-xs text-slate-600">完整 Secret 仅展示一次，请妥善保存：</p><code className="block break-all rounded-2xl border border-slate-800 bg-slate-900 p-4 text-xs font-bold text-emerald-400">{secret}</code></Modal> : null}
  </section>;
}
