"use client";

import { useMemo, useState, type FormEvent } from "react";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Modal } from "@/components/ui/modal";
import { Select } from "@/components/ui/select";
import { Tag } from "@/components/ui/tag";
import { Icon } from "@/components/ui/icon";
import { usePortal } from "@/components/portal/portal-context";
import type { ReaderScenario, SearchScenario } from "@/types/portal";

type Result = { title: string; url: string; description: string; engines: string[] };
type Reader = { url: string; title: string; content: string; finalUrl: string; contentType: string; truncated: boolean };
const isUrl = (value: string) => /^https?:\/\/[^\s]+$/i.test(value.trim());
const time = (value: string, locale: string) => new Intl.DateTimeFormat(locale, { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const previewMessage: Record<Exclude<SearchScenario, "success">, string> = { empty: "请求成功，但没有匹配结果。", partial: "Brave：429 Too Many Requests", timeout: "搜索运行时未在设定时间内返回结果。", rate_limited: "当前请求超过引擎或入口的限流额度。", proxy: "搜索运行时代理连接失败。", runtime: "Open-WebSearch Runtime 未就绪。", failed: "所有已选搜索引擎均未返回可用结果。" };
const readerMessage: Partial<Record<ReaderScenario, string>> = { blocked: "URL 不允许访问", dns: "DNS 解析到私网 IP，已由 SSRF 防护拦截", redirect: "重定向目标不允许访问", tls: "TLS 证书校验失败", extract: "无法提取网页正文", timeout: "抓取请求超时", refused: "目标站拒绝连接" };
const engineTagClass: Record<string, string> = { Bing: "engine-tag-bing", DuckDuckGo: "engine-tag-duckduckgo", Baidu: "engine-tag-baidu", Exa: "engine-tag-exa", Brave: "engine-tag-brave", CSDN: "engine-tag-csdn", Juejin: "engine-tag-juejin", Sogou: "engine-tag-sogou", Startpage: "engine-tag-startpage" };

export function SearchPage() {
  const { engines, settings, history, locale, notify, refresh } = usePortal();
  const english = locale === "en";
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [limit, setLimit] = useState(String(settings.defaultLimit)); const [bingMode, setBingMode] = useState<"auto" | "request">("request");
  const [results, setResults] = useState<Result[]>([]); const [failures, setFailures] = useState<Array<{ engine: string; message: string }>>([]); const [elapsed, setElapsed] = useState<number | null>(null); const [loading, setLoading] = useState(false); const [scenario, setScenario] = useState<SearchScenario>("success");
  const [reader, setReader] = useState<Reader | null>(null); const [readerScenario, setReaderScenario] = useState<ReaderScenario>("success"); const [historyOpen, setHistoryOpen] = useState(false);
  const defaults = useMemo(() => engines.filter((engine) => engine.enabled && engine.isDefault).map((engine) => engine.id), [engines]);
  const active = (selected.filter((id) => engines.some((engine) => engine.id === id && engine.enabled))).length ? selected.filter((id) => engines.some((engine) => engine.id === id && engine.enabled)) : defaults;
  const t = english ? { title: "Multi-engine Web Search", subtitle: "Aggregate Bing, Baidu, DuckDuckGo and other upstream sources", search: "Search", restore: "Restore defaults", read: "Read content", history: "Search history" } : { title: "lazycat-search Portal", subtitle: "聚合 Bing、Baidu、DuckDuckGo 等 9 大无 Key 搜索源", search: "搜索", restore: "一键恢复默认", read: "读取正文", history: "搜索历史" };
  const toggle = (id: string) => setSelected((current) => { const base = current.length ? current : defaults; return base.includes(id) ? base.filter((item) => item !== id) : [...base, id]; });
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!query.trim()) return notify(english ? "Enter a search query first." : "请先输入搜索关键词。", "info"); if (!active.length) return notify(english ? "Select an enabled engine." : "请至少选择一个已启用的搜索引擎。", "error"); setLoading(true); setFailures([]); setScenario("success"); const started = performance.now(); try { const data = await api.search({ query: query.trim(), engines: active, limit: Number(limit), searchMode: active.includes("bing") ? "request" : undefined }); setResults(data.results); setFailures(data.failures); setElapsed(Math.round(performance.now() - started)); await refresh(); if (bingMode === "auto" && active.includes("bing")) notify(english ? "Auto is displayed for prototype parity; this local runtime safely uses Request mode." : "为保持原型选项，界面显示 Auto；本地运行时会安全地使用 Request 模式。", "info"); else if (data.cached) notify(english ? "Results were returned from cache." : "已从缓存返回结果。", "info"); } catch (error) { setElapsed(Math.round(performance.now() - started)); setScenario("failed"); notify(error instanceof Error ? error.message : "搜索失败", "error"); } finally { setLoading(false); } };
  const read = async (url: string, title: string) => { setReaderScenario("success"); try { const data = await api.fetchContent(url); setReader({ url, title: data.content.title || title, content: data.content.content, finalUrl: data.content.finalUrl, contentType: data.content.contentType, truncated: data.content.truncated }); } catch (error) { notify(error instanceof Error ? error.message : "正文读取失败", "error"); } };
  const clearHistory = async () => { try { await api.clearHistory(); await refresh(); notify(english ? "Search history cleared." : "搜索历史已清除。"); } catch (error) { notify(error instanceof Error ? error.message : "清除失败", "error"); } };
  const preview = scenario !== "success" ? previewMessage[scenario] : ""; const visibleResults = scenario === "success" || scenario === "partial" ? results : [];
  return <section className="mx-auto max-w-4xl space-y-6 pb-16">
    <div className="py-4 text-center"><h1 className="text-3xl font-extrabold tracking-tight text-slate-900">{t.title}</h1><p className="mt-1 text-xs text-slate-500">{t.subtitle}</p></div>
    <Card className="rounded-2xl border-2 border-slate-200/90 p-4 shadow-md transition-colors hover:border-blue-400 focus-within:border-blue-600 focus-within:ring-4 focus-within:ring-blue-500/15"><form onSubmit={submit} className="flex flex-col items-stretch sm:flex-row"><div className="flex min-w-0 flex-1 items-center px-2 py-1"><Icon name="magnifying-glass" className="mr-3 text-xl text-blue-600" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={english ? "Enter a query, or paste a complete URL…" : "输入搜索关键词，或直接粘贴网页 URL..."} className="min-h-10 w-full border-0 bg-transparent text-base font-medium text-slate-800 outline-none placeholder:text-slate-400" />{query ? <button type="button" onClick={() => setQuery("")} className="mr-1 text-lg text-slate-400 hover:text-slate-600" aria-label={english ? "Clear" : "清除"}><Icon name="x-circle" /></button> : null}</div><div className="mt-2 flex items-center justify-between gap-2 border-t border-slate-200 pt-2.5 sm:mt-0 sm:border-t-0 sm:border-l sm:pt-0 sm:pl-3"><button type="button" onClick={() => setHistoryOpen(true)} className="rounded-xl p-2.5 text-lg text-slate-500 hover:bg-blue-50 hover:text-blue-600" aria-label={t.history}><Icon name="clock-counter-clockwise" /></button><Button type="submit" disabled={loading} className="min-w-24 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-600 shadow-md shadow-blue-600/30">{loading ? "…" : t.search} <Icon name="paper-plane-right" /></Button></div></form>{isUrl(query) ? <div className="mt-3 flex flex-wrap items-center justify-between gap-2 rounded-xl border border-blue-100 bg-blue-50 px-3 py-2 text-xs text-blue-900"><span className="flex items-center font-medium"><Icon name="link-simple" className="mr-2 text-base text-blue-600" />{english ? "A complete URL was detected. You can read its content directly." : "检测到输入为完整 URL，可直接读取网页正文"}</span><Button type="button" className="min-h-7 rounded-lg px-3 py-1 text-[11px]" onClick={() => void read(query.trim(), query.trim())}><Icon name="file-text" /> {t.read}</Button></div> : null}</Card>
    <Card className="space-y-4 rounded-2xl p-5 text-xs"><div className="flex items-center justify-between border-b border-slate-100 pb-2"><span className="flex items-center font-bold text-slate-800"><Icon name="sliders-horizontal" weight="fill" className="mr-1.5 text-blue-600" />{english ? "Search engine selection (Providers)" : "搜索引擎多选 (Providers)"}</span><button type="button" onClick={() => setSelected([])} className="flex items-center font-semibold text-blue-600 hover:text-blue-800"><Icon name="arrow-counter-clockwise" className="mr-1" />{t.restore}</button></div><div className="flex flex-wrap gap-2">{engines.map((engine) => <button key={engine.id} type="button" disabled={!engine.enabled} onClick={() => toggle(engine.id)} className={`rounded-full border px-3 py-1.5 text-[11px] font-bold transition active:scale-95 disabled:opacity-40 ${active.includes(engine.id) ? "border-blue-200 bg-blue-50 text-blue-700" : "border-slate-200 bg-white text-slate-600"}`}>{active.includes(engine.id) ? "✓ " : ""}{engine.name}</button>)}</div><p className="flex items-center text-[10px] text-slate-400"><Icon name="info" className="mr-1 text-blue-500" />{english ? "Linux.do search is hidden when disabled; its dedicated reader tool can remain available." : "Linux.do 搜索上游暂不可用已默认隐藏，其单篇正文提取 fetchLinuxDoArticle 正常可用。"}</p><div className="grid gap-4 border-t border-slate-100 pt-3 sm:grid-cols-2"><label className="font-semibold text-slate-600">{english ? "Result limit" : "返回数量上限 (Limit)"}<Select value={limit} onChange={(event) => setLimit(event.target.value)} className="mt-1 w-full rounded-xl"><option value="5">5 {english ? "results" : "条（极速）"}</option><option value="10">10 {english ? "results" : "条（默认推荐）"}</option><option value="20">20 {english ? "results" : "条（深度覆盖）"}</option><option value="30">30 {english ? "results" : "条"}</option><option value="50">50 {english ? "results" : "条（后端最大上限）"}</option></Select></label><label className="font-semibold text-slate-600">Bing Search Mode ({english ? "advanced" : "高级选项"})<span className="float-right font-mono text-[10px] text-blue-600">{english ? "Bing only" : "仅 Bing 选中时生效"}</span><Select value={bingMode} onChange={(event) => setBingMode(event.target.value as "auto" | "request")} className="mt-1 w-full rounded-xl border-blue-200 bg-blue-50/50 text-blue-900"><option value="auto">Auto ({english ? "system default" : "系统配置默认"})</option><option value="request">Request ({english ? "native HTTP" : "原生 HTTP"})</option></Select></label></div></Card>
    {elapsed !== null ? <div className="space-y-4">{(failures.length || scenario === "partial") ? <div className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-900"><Icon name="warning-circle" className="text-lg" /><div><strong>{english ? "Some search engines did not respond" : "部分搜索引擎响应失败（单源失败不影响其他源）"}</strong><p className="mt-1 font-mono text-[11px]">{scenario === "partial" ? preview : failures.map((item) => `${item.engine}: ${item.message}`).join(" · ")}</p></div></div> : null}<div className="flex items-center justify-between px-1 text-xs text-slate-500"><span>{english ? "Found" : "找到约"} <strong className="font-mono text-blue-600">{visibleResults.length}</strong> {english ? "merged results" : "条聚合结果"}（{elapsed}ms）</span><span className="text-slate-400">{english ? "URLs merged across engines" : "已对多引擎 URL 去重合并"}</span></div><div className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-slate-200 bg-slate-100/80 p-3 text-xs text-slate-600"><span className="font-semibold">{english ? "Prototype status preview:" : "模拟状态选择:"}</span><div className="flex flex-wrap gap-1 font-mono text-[11px]">{(["success", "empty", "failed", "timeout", "rate_limited", "proxy", "runtime"] as SearchScenario[]).map((item) => <button key={item} type="button" onClick={() => setScenario(item)} className={`rounded border px-2 py-0.5 ${scenario === item ? "border-blue-400 bg-blue-50 text-blue-700" : "bg-white hover:border-blue-400"}`}>{({ success: "正常多源结果", empty: "成功但无结果", failed: "所有源均失败", timeout: "网络超时", rate_limited: "引擎限流", proxy: "代理异常", runtime: "运行时启动失败" } as Record<string, string>)[item]}</button>)}</div></div>{preview && scenario !== "partial" ? <Card className="rounded-2xl border-amber-200 bg-amber-50 p-6 text-center text-xs text-amber-900">{preview}</Card> : null}{visibleResults.map((result) => <Card key={result.url} className="rounded-2xl p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div className="min-w-0"><a href={result.url} target="_blank" rel="noreferrer" className="text-sm font-extrabold text-blue-700 hover:underline">{result.title}</a><p className="mt-1 truncate font-mono text-[11px] text-emerald-700">{result.url}</p><p className="mt-2 text-xs leading-5 text-slate-600">{result.description}</p><div className="mt-3 flex flex-wrap gap-1.5">{result.engines.map((engine) => <Tag key={engine} tone="blue" className={engineTagClass[engine]}>{engine}</Tag>)}</div></div><Button variant="secondary" className="self-start text-[11px]" onClick={() => void read(result.url, result.title)}><Icon name="file-text" /> {t.read}</Button></div></Card>)}</div> : null}
    {reader ? <Modal title={reader.title} onClose={() => setReader(null)} className="h-[85vh] max-w-4xl" bodyClassName="flex min-h-0 flex-1 flex-col overflow-hidden p-0" headerExtra={<div className="mt-1 space-y-1 text-[11px] text-slate-500"><div className="flex gap-2"><span className="text-slate-400">原始 URL</span><a href={reader.url} target="_blank" rel="noreferrer" className="truncate font-mono hover:text-blue-600 hover:underline">{reader.url}</a></div><div className="flex flex-wrap gap-2"><span className="text-slate-400">最终 URL</span><a href={reader.finalUrl} target="_blank" rel="noreferrer" className="max-w-80 truncate font-mono hover:text-blue-600 hover:underline">{reader.finalUrl}</a><Tag tone="neutral">{reader.contentType || "text/html"}</Tag><Tag tone={reader.truncated ? "amber" : "blue"}>{reader.truncated ? "已截断" : "未截断"}</Tag></div></div>} footer={<><Button variant="secondary" onClick={() => void navigator.clipboard?.writeText(reader.content)}>复制正文</Button><a href={reader.url} target="_blank" rel="noreferrer" className="inline-flex"><Button>打开源站</Button></a></>}><div className="flex items-center justify-between border-b border-slate-200 bg-slate-100 px-5 py-2.5 text-xs"><span className="font-semibold text-slate-600">抓取状态模拟:</span><Select className="min-h-7 bg-white py-0 text-[11px]" value={readerScenario} onChange={(event) => setReaderScenario(event.target.value as ReaderScenario)}><option value="success">正常抓取成功</option><option value="blocked">URL 不允许访问</option><option value="dns">DNS 解析到私网 IP</option><option value="redirect">重定向被阻止</option><option value="tls">TLS 证书错误</option><option value="extract">无法提取正文</option><option value="timeout">抓取超时</option></Select></div>{readerScenario !== "success" ? <div className="m-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{readerMessage[readerScenario]}</div> : <article className="min-h-0 flex-1 overflow-y-auto whitespace-pre-wrap p-6 text-sm font-medium leading-7 text-slate-800">{reader.content}</article>}</Modal> : null}
    {historyOpen ? <Modal title={t.history} onClose={() => setHistoryOpen(false)} className="max-w-2xl" bodyClassName="max-h-[60vh] overflow-y-auto" footer={<Button variant="secondary" onClick={() => setHistoryOpen(false)}>关闭</Button>} headerExtra={<button type="button" onClick={() => void clearHistory()} className="mt-1 text-xs font-semibold text-red-600 hover:underline">清空历史</button>}><div className="space-y-2">{history.length ? history.map((item) => <button key={item.id} type="button" onClick={() => { setQuery(item.query); setHistoryOpen(false); }} className="block w-full rounded-xl border border-slate-100 p-3 text-left hover:border-blue-200 hover:bg-blue-50"><p className="truncate text-xs font-bold text-slate-800">{item.query}</p><p className="mt-1 text-[10px] text-slate-400">{time(item.createdAt, english ? "en-US" : "zh-CN")} · {item.count} {english ? "results" : "条结果"} · {item.engines.join(", ")}</p></button>) : <p className="py-8 text-center text-xs text-slate-400">暂无已保存的搜索历史。</p>}</div></Modal> : null}
  </section>;
}
