"use client";

import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Icon } from "@/components/ui/icon";
import { usePortal } from "@/components/portal/portal-context";
import type { SettingsState } from "@/types/portal";

function NumberField({ label, value, onChange, help }: { label: string; value: number; onChange: (value: number) => void; help?: string }) {
  return <label className="text-xs font-bold text-slate-700">{label}<Input className="mt-1" type="number" min={1} value={value} onChange={(event) => onChange(Math.max(1, Number(event.target.value)))} />{help ? <span className="mt-1 block text-[10px] font-normal leading-4 text-slate-400">{help}</span> : null}</label>;
}

export function SettingsPage() {
  const { settings, setSettings, engines, locale, notify, refresh } = usePortal(); const english = locale === "en";
  const update = <K extends keyof SettingsState>(key: K, value: SettingsState[K]) => setSettings((current) => ({ ...current, [key]: value }));
  const save = async () => { try { const saved = await api.updateSettings(settings); setSettings(saved); await refresh(); notify(english ? "System settings saved." : "系统参数已保存。"); } catch (error) { notify(error instanceof Error ? error.message : "保存失败", "error"); } };
  const clearHistory = async () => { try { await api.clearHistory(); await refresh(); notify(english ? "Search history cleared." : "搜索历史已清除。"); } catch (error) { notify(error instanceof Error ? error.message : "清除失败", "error"); } };
  const testProxy = () => { if (!settings.proxyEnabled || !settings.proxyUrl) { notify(english ? "Enable the proxy and enter its URL first." : "请先启用代理并填写地址。", "error"); return; } try { new URL(settings.proxyUrl); notify(english ? "URL format is valid. This local runtime has no standalone proxy-test endpoint." : "代理地址格式有效；当前本地运行时未提供独立的代理测试接口。", "info"); } catch { notify(english ? "Enter a complete proxy URL." : "请输入完整的代理地址。", "error"); } };
  const toggleDefault = async (id: string, isDefault: boolean) => { try { await api.updateEngine(id, { isDefault }); await refresh(); } catch (error) { notify(error instanceof Error ? error.message : "更新失败", "error"); } };
  const t = english ? { title: "System settings", subtitle: "Configure proxy, cache policy, rate limits, defaults, and data retention", cache: "Cache policy", rate: "Rate limits", defaults: "Search defaults", data: "Data management", save: "Save system settings" } : { title: "系统参数配置 (System Settings)", subtitle: "控制 Search Runtime Proxy、缓存 TTL、限流策略与数据保留期", cache: "缓存策略", rate: "限流策略", defaults: "默认搜索参数", data: "数据管理", save: "保存系统参数" };
  return <section className="mx-auto max-w-4xl space-y-6">
    <div><h1 className="text-2xl font-extrabold tracking-tight text-slate-900">{t.title}</h1><p className="mt-1 text-xs text-slate-500">{t.subtitle}</p></div>
    <Card className="rounded-2xl p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-sm font-bold text-slate-900">Network & Proxy</h2><p className="mt-1 text-xs text-slate-500">{english ? "Store the runtime proxy configuration. The value is masked after it is saved." : "保存搜索运行时的代理配置；保存后敏感内容会被掩码显示。"}</p></div><div className="flex items-center gap-2 rounded-xl bg-slate-50 p-2"><span className="text-xs font-bold text-slate-700">{english ? "Enable proxy" : "启用搜索代理"}</span><Switch label="proxy" checked={settings.proxyEnabled} onChange={(value) => update("proxyEnabled", value)} /></div></div><div className="mt-4 flex flex-wrap gap-2"><label className="min-w-[250px] flex-1 text-xs font-bold text-slate-700">Proxy URL<Input className="mt-1 font-mono text-xs" disabled={!settings.proxyEnabled} placeholder="http://127.0.0.1:7890" value={settings.proxyUrl} onChange={(event) => update("proxyUrl", event.target.value)} /></label><Button variant="secondary" className="self-end" onClick={testProxy}>↻ {english ? "Test proxy" : "测试代理"}</Button></div><p className="mt-2 text-[10px] leading-4 text-slate-400">{english ? "The current backend stores this value; applying it to an external search runtime requires the runtime configuration to be reloaded." : "当前后端会保存此值；外部搜索运行时需要重新加载配置后才会采用代理。"}</p></Card>
    <Card className="rounded-2xl p-5"><h2 className="text-sm font-bold text-slate-900">{t.cache}</h2><p className="mt-1 text-xs text-slate-500">{english ? "Search cache keys include query, engines, limit, and search mode. Web and MCP share the same policy." : "搜索缓存 Key 包含 query、engines、limit 与 searchMode；MCP 和 Web 共享缓存。"}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><ToggleRow label={english ? "Enable search cache" : "启用搜索结果缓存"} checked={settings.searchCacheEnabled} onChange={(value) => update("searchCacheEnabled", value)} /><ToggleRow label={english ? "Enable content cache" : "启用正文缓存"} checked={settings.contentCacheEnabled} onChange={(value) => update("contentCacheEnabled", value)} /><NumberField label={english ? "Search cache TTL (seconds)" : "搜索缓存 TTL（秒）"} value={settings.searchTtl} onChange={(value) => update("searchTtl", value)} /><NumberField label={english ? "Content cache TTL (seconds)" : "正文缓存 TTL（秒）"} value={settings.contentTtl} onChange={(value) => update("contentTtl", value)} /><NumberField label={english ? "Maximum cache entries" : "缓存条目上限"} value={settings.cacheMaxSize} onChange={(value) => update("cacheMaxSize", value)} /></div></Card>
    <Card className="rounded-2xl p-5"><h2 className="text-sm font-bold text-slate-900">{t.rate}</h2><p className="mt-1 text-xs text-slate-500">{english ? "These limits protect the local management service and MCP Token access." : "这些限制用于保护本地管理服务与 MCP Token 调用。"}</p><div className="mt-4 grid gap-3 md:grid-cols-3"><NumberField label={english ? "Web / IP (per minute)" : "Web / IP（每分钟）"} value={settings.webRpm} onChange={(value) => update("webRpm", value)} /><NumberField label={english ? "MCP / Token (per minute)" : "MCP / Token（每分钟）"} value={settings.mcpRpm} onChange={(value) => update("mcpRpm", value)} /><NumberField label={english ? "Per-engine concurrency" : "单引擎并发数"} value={settings.engineConcurrency} onChange={(value) => update("engineConcurrency", value)} /></div></Card>
    <Card className="rounded-2xl p-5"><h2 className="text-sm font-bold text-slate-900">{t.defaults}</h2><p className="mt-1 text-xs text-slate-500">{english ? "Choose the default engines used when no provider is explicitly selected." : "未手动选择引擎时，将使用这里设置的默认引擎。"}</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{engines.map((engine) => <ToggleRow key={engine.id} label={engine.name} checked={engine.isDefault} onChange={(value) => void toggleDefault(engine.id, value)} />)}</div><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold text-slate-700">{english ? "Default result count" : "默认返回数量"}<Select className="mt-1 w-full" value={settings.defaultLimit} onChange={(event) => update("defaultLimit", Number(event.target.value))}><option value={10}>10</option><option value={20}>20</option><option value={30}>30</option></Select></label><div className="rounded-xl border border-blue-100 bg-blue-50 px-3 py-2 text-xs text-blue-900"><strong>Bing Search Mode:</strong> Request（原生 HTTP）</div></div></Card>
    <Card className="rounded-2xl p-5"><h2 className="text-sm font-bold text-slate-900">{t.data}</h2><p className="mt-1 text-xs text-slate-500">{english ? "History can be cleared immediately. Retention and log fields apply to future records." : "搜索历史可以立即清除；保留期和日志字段配置会用于后续记录。"}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><ToggleRow label={english ? "Save search history" : "保存搜索历史"} checked={settings.historyEnabled} onChange={(value) => update("historyEnabled", value)} /><ToggleRow label={english ? "Store full query in logs" : "在日志中记录完整 Query"} checked={settings.logFullQuery} onChange={(value) => update("logFullQuery", value)} /><label className="text-xs font-bold text-slate-700">{english ? "History retention" : "搜索历史保留期"}<Select className="mt-1 w-full" value={settings.historyRetentionDays} onChange={(event) => update("historyRetentionDays", Number(event.target.value))}><option value={7}>7 {english ? "days" : "天"}</option><option value={30}>30 {english ? "days" : "天"}</option><option value={90}>90 {english ? "days" : "天"}</option></Select></label></div><div className="mt-4 border-t border-slate-100 pt-4"><Button variant="danger" onClick={() => void clearHistory()}><Icon name="trash" /> {english ? "Clear search history now" : "立即清除搜索历史"}</Button></div></Card>
    <div className="sticky bottom-4 z-10 flex justify-end"><Button className="rounded-xl px-5 shadow-lg shadow-blue-600/25" onClick={() => void save()}><Icon name="check" /> {t.save}</Button></div>
  </section>;
}

function ToggleRow({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) {
  return <div className="flex items-center justify-between rounded-xl border border-slate-100 bg-slate-50 px-3 py-2.5"><span className="text-xs font-bold text-slate-700">{label}</span><Switch label={label} checked={checked} onChange={onChange} /></div>;
}
